CREATE TABLE IF NOT EXISTS inbound_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(64) NOT NULL,
  raw_action VARCHAR(128) NOT NULL,
  organization_id VARCHAR(128) NULL,
  chat_id VARCHAR(128) NULL,
  thread_id VARCHAR(128) NULL,
  event_id VARCHAR(128) NULL,
  event_type VARCHAR(64) NULL,
  standard_event_type VARCHAR(64) NOT NULL,
  author_id VARCHAR(128) NULL,
  sender_role VARCHAR(64) NOT NULL,
  occurred_at DATETIME(6) NULL,
  dedup_key VARCHAR(255) NOT NULL,
  payload_json JSON NOT NULL,
  ignored TINYINT(1) NOT NULL DEFAULT 0,
  ignore_reason VARCHAR(128) NULL,
  processed TINYINT(1) NOT NULL DEFAULT 0,
  leased_at DATETIME(6) NULL,
  lease_expires_at DATETIME(6) NULL,
  locked_by VARCHAR(128) NULL,
  attempted_at DATETIME(6) NULL,
  processed_at DATETIME(6) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_dedup_key (dedup_key),
  KEY idx_processed_ignored_id (processed, ignored, id),
  KEY idx_inbound_events_processed_lease_id (processed, ignored, lease_expires_at, id),
  KEY idx_inbound_events_locked_by (locked_by),
  KEY idx_inbound_events_chat_lease_id (chat_id, processed, lease_expires_at, id),
  KEY idx_chat_thread (chat_id, thread_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
