CREATE TABLE IF NOT EXISTS livechat_webhook_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  webhook_id VARCHAR(128) NULL,
  action VARCHAR(128) NULL,
  organization_id VARCHAR(128) NULL,
  chat_id VARCHAR(128) NULL,
  thread_id VARCHAR(128) NULL,
  event_id VARCHAR(128) NULL,
  event_type VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
  http_status INT NULL,
  normalized_count INT NOT NULL DEFAULT 0,
  inserted_count INT NOT NULL DEFAULT 0,
  duplicate_count INT NOT NULL DEFAULT 0,
  ignored_count INT NOT NULL DEFAULT 0,
  error_type VARCHAR(128) NULL,
  error_message TEXT NULL,
  payload_json JSON NULL,
  received_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_livechat_webhook_audit_received (received_at),
  KEY idx_livechat_webhook_audit_action_received (action, received_at),
  KEY idx_livechat_webhook_audit_status_received (status, received_at),
  KEY idx_livechat_webhook_audit_chat_thread (chat_id, thread_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
